#---
#homebrew_installed_packages:
#  - autoconf
#  - bash-completion
#  - gettext
#  - sqlite
#  - ssh-copy-id
#  - cowsay
#  - readline
#  - pv
#  - wget
#  - wrk
#
#homebrew_cask_apps:
#  - firefox
#  - licecap

osx_defaults:
  - { domain: NSGlobalDomain, key: AppleInterfaceStyle, type: string, value: Dark }
  - { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
  - { domain: com.apple.finder, key: ShowHardDrivesOnDesktop type: bool, value: true }
#  - { domain: com.apple.finder, key: ShowMountedServersOnDesktop, type: bool, value: true }
#  - { domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, type: bool, value: true }
#  - { domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: true }
#  - { domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
