---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Photos
  - Maps
  - Facetime
  - Contacts
  - Notes
dockitems_persist: []
- name: "Audio MIDI Setup"
  path: "/Applications/Utilities/Audio MIDI Setup.app/"
  pos: 11

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/S-git1/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
#  - .zshrc
#  - .gitignore
#  - .inputrc
  - .osx
#  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
 - exiftool
 - iperf
#  - autoconf
#  - bash-completion
#  - doxygen
#  - gettext
#  - gifsicle
#  - git
#  - github/gh/gh
#  - go
#  - gpg
#  - httpie

#  - libevent
#  - sqlite
#  - mcrypt
#  - nmap
#  - node
#  - nvm
#  - php
#  - ssh-copy-id
#  - cowsay
#  - readline
#  - openssl
#  - pv
#  - wget
#  - wrk
#  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
#  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - transmission
  - grandperspective
  - latest
  - appcleaner
  - iina
  - karabiner-elements
  - scroll-reverser
  - google-drive
  - onedrive
  - microsoft-excel
  - microsoft-word
  - microsoft-powerpoint
  - r
  - rstudio
  - balenaetcher
  - radio-silence
  - vnc-viewer
  - tailscale
  - notion
  - obs
  - visual-studio-code
#  - licecap
#  - sequel-ace
#  - slack
#  - sublime-text
#  - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_upgrade_all_apps: true # newly added in attempt to get mas_unistalled_apps to run without skipping

mas_uninstalled_apps: # special permimssion required to unistalled App Store installed apps? Does not work, seems to be bug
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }
  
mas_installed_apps:
  - { id: 1333542190, name: "1Password 7" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 975890633, name: "HotKey" }
  - { id: 1295203466, name: "Microsoft Remote Desktop" }
  - { id: 1099568401, name: "Home Assistant" }
  - { id: 1319778037, name: "iStat Menus" }
  - { id: 470158793, name: "Keka" }
  - { id: 1365531024, name: "1Blocker" }
  - { id: 1251572132, name: "Fresco" }
  - { id: 1176895641, name: "Spark" }
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 869223134, name: "KakaoTalk" }
  - { id: 497799835, name: "Xcode" }

mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# choose one or the other to run command line commands in .osx or use Ansible tasks
osx_use_dotfile: false
osx_use_defaults: true

osx_defaults: #[]
  - { domain: NSGlobalDomain, key: AppleInterfaceStyle, type: string, value: Dark }
  - { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
  - { domain: com.apple.finder, key: ShowHardDrivesOnDesktop, type: bool, value: true }

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
